spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
